/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */
public with sharing class sdgLabels {
    // attribute simply to force inclusion within package
    public static   List<String> strings = new List<String>{
        Label.sdgAfter,
            Label.sdgBefore,
            Label.sdgContains,
            Label.sdgEnds,
            Label.sdgEquals,
            Label.sdgFalse,
            Label.sdgFiltered,
            Label.sdgFilteredOf,
            Label.sdgGreaterThan,
            Label.sdgLastMonth,
            Label.sdgLastQuarter,
            Label.sdgLastWeek,
            Label.sdgLastYear,
            Label.sdgLessThan,
            Label.sdgNextMonth,
            Label.sdgNextQuarter,
            Label.sdgNextWeek,
            Label.sdgNextYear,
            Label.sdgNoData,
            Label.sdgNotContains,
            Label.sdgNotEquals,
            Label.sdgPage,
            Label.sdgPage_Size,
            Label.sdgStarts,
            Label.sdgThisMonth,
            Label.sdgThisQuarter,
            Label.sdgThisWeek,
            Label.sdgThisYear,
            Label.sdgToday,
            Label.sdgTomorrow,
            Label.sdgTrue,
            Label.sdgYesterday,
            Label.sdgIn,
            Label.sdgAgo
            };

                }